[web]

18.215.117.6
3.237.202.187

[web:vars]

ansible_user=ubuntu
ansible_ssh_private_key_file=/home/michael/aws/devops-lab-key.pem

[app]



[app:vars]

ansible_user=ubuntu
ansible_ssh_private_key_file=/home/michael/aws/devops-lab-key.pem
