name: Pipeline

on:
  push:

jobs:

  validate:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - run: ./scripts/check_notes.sh

  docker:

    runs-on: ubuntu-latest

    needs: validate

    steps:

      - uses: actions/checkout@v4

      - run: docker build -t devops-test .
