name: Ansible Validate

on:
  pull_request:
    paths:
      - 'ansible-demo/**'
      - 'terraform-ci-demo/ansible/**'
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Validate ansible-demo Playbook
        working-directory: ansible-demo
        run: ansible-playbook playbook.yml --syntax-check

      - name: Validate terraform-ci-demo ansible playbooks
        working-directory: terraform-ci-demo/ansible
        run: ansible-playbook playbook.yml --syntax-check
