name: Test GitHub Secrets

on:
  workflow_dispatch:

jobs:
  test-secrets:

    runs-on: ubuntu-latest

    steps:

      - name: Verify Secrets Exist
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}


        run: |
          if [ -n "$AWS_ACCESS_KEY_ID" ]; then
            echo "AWS Access Key Loaded"
          else
            echo "Missing Access Key"
            exit 1
          fi

          if [ -n "$AWS_SECRET_ACCESS_KEY" ]; then
            echo "AWS Secret Loaded"
          else
            echo "Missing Secret"
          fi

          echo "Region: $AWS_REGION"
