name: Terraform Validate

on:

  push:

    branches:
      - main
      - day21-iac-pipeline

    paths:
      - 'terraform-ci-demo/**'

  pull_request:

    paths:
      - 'terraform-ci-demo/**'

    branches:
      - main
jobs:

  terraform:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform-ci-demo/terraform


    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6

        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Formatting
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color -var-file="environments/dev.tfvars"
        env:
          TF_VAR_my_ip: ${{ secrets.MY_IP }}
