name: Validate Repository

on:
  push:

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Validation
        run: ./scripts/check_notes.sh
